### ISSUE TITLE
This website can't load the data set.

### ISSUE THREAD

**Issue by Applesuger** [connectomicslab/Aneurysm_Detection#1]
Hello.This website can't load the data set, but it was useful before. Could you share the data set? Thanks!
“https://openneuro.org/datasets/ds003821”

**Comment by tommydino93** [comment]
Hi @Applesuger,
Thanks for your interest in the project. I had to remove the dataset because of some de-identification issues. It will be available again soon (i.e. this week)

**Comment by tommydino93** [comment]
It should be available now

**Comment by Applesuger** [comment]
> It should be available now (https://openneuro.org/datasets/ds003949)

Thank you for your attention to this matter
